apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: waascodeploy-daemon
spec:
  selector:
    matchLabels:
      app: waascodeploy
  template:
    metadata:
      labels:
        app: waascodeploy
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      # need high priority
      priorityClassName: system-node-critical
      # check processes to ensure all cgroups managed by us are created by docker/containerd/k8s
      hostPID: true 
      containers:
      - name: waascodeploy
        image: waascodeploy:1.0.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        securityContext:
          runAsUser: 0 # need root to r/w cgroup info
        volumeMounts:
        - name: host-cgroup
          mountPath: /sys/fs/cgroup
          readOnly: false
        - name: host-var
          mountPath: /var/run
          readOnly: false
        - name: host-resctrl
          mountPath: /sys/fs/resctrl
          readOnly: false
      terminationGracePeriodSeconds: 15
      volumes:
      - name: host-cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      - name: host-var
        hostPath:
          path: /var/run
          type: Directory
      - name: host-resctrl
        hostPath:
          path: /sys/fs/resctrl
          type: Directory